Repository GitMetricsLab/github_tracker, pull requests merged in 2025-07, with the labels that each got.

#114 login UI
  package.json
  src/Routes/Login/Login.tsx
Labels: gssoc2025, level2

#119 Signup UI
  src/Routes/Signup/Signup.tsx
Labels: gssoc2025, level2

#123 Added UserProfile component and integrated it with Contributor PR linking
  src/App.tsx
  src/Routes/Router.tsx
  src/pages/Contributors/Contributors.tsx
  src/pages/UserProfile/UserProfile.tsx
Labels: gssoc2025, level3

#125 Add comprehensive Jasmine backend test suite: User model, auth routes,Passport integration.
  README.md
  package.json
  spec/auth.routes.spec.cjs
  spec/support/jasmine.mjs
  spec/user.model.spec.cjs
Labels: goodwork, gssoc2025, level2

#132 Feature: Add shareable link to user’s PRs
  package.json
  src/pages/UserProfile/UserProfile.tsx
Labels: gssoc2025

#138 fixed: theme switch bug for login & contributors pages respectively
  src/App.tsx
  src/components/Navbar.tsx
  src/context/ThemeContext.tsx
  src/hooks/useTheme.ts
  src/main.tsx
  src/pages/Contact/Contact.tsx
  src/pages/Contributors/Contributors.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
Labels: gssoc2025

#149 ⚡ Optimize fetchData: use Promise.all and safe pagination
  src/hooks/useGitHubData.ts
  src/hooks/usePagination.ts
  src/pages/Home/Home.tsx
Labels: gssoc25, level2
